CREATE TABLE public.notes (
	id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	title varchar NOT NULL,
	body varchar NULL,
	children integer[] NULL,
	CONSTRAINT notesnodes_pk PRIMARY KEY (id)
);
